#+TITLE: 9月尾声

* 爱国
#+begin_quote
首先，要搞清楚一个定义问题:什么是爱国？如果“国”，是指这九百六十万平方公里上的土地与海洋，是指上面的阳光与空气，指上面的大好河山，谁闲得蛋疼不爱它们呢？
如果"国"，是指这几千年积累下来的诗词歌赋、英雄传说、亭台楼阁，谁又这么无趣不爱它们呢？
如果“国”，是指我们这十几亿的劳动者，他们可能是流水线上的工人、可能是写字楼里的码农、是医生、是教师，谁又莫名其妙地不爱自己呢？
所以爱国之所以有争论，是因为总有一群人，一群本应该保护好这片环境、弘扬优秀文化、为人民服务的那群人——在宣传上，把自己与这些可爱的事物捆绑起来，拿他们当挡箭牌。
当他们没尽到责任，甚至搞破坏、搞限制、不好好服务的时候。
大家要批评它两句，并进一步讨论，把以上这一切授权给他们管理，到底合适不合适（毕竟整个授权过程里面，我们只能形式上地假装自己参与了）。
这时候、他们和他们的养的文人、和轻信这套的人，就会跳出来说:“哎你不爱国！”
#+end_quote

* 真正的狭隘
  真正的狭隘者，往往并不明白世上本没有狭隘，一切皆不过是感情使然。人总趋向于获得安全感。

  对对方的心情，不能设身处地的考虑过或考虑的过程太痛苦，便给别人安个狭隘的头衔，实际上也是一件十分愉悦以及轻松的事情。

* 人不自觉地言不由衷
  说a指b。实际上皆为内心的郁结，而内心郁结多来源于对生活的焦虑。

  但这并不值得鄙视，焦虑的社会，就如鄙人之前所转的那篇关于教育的文章一般。指责社会中焦虑的个体是没有意义的。焦虑的根源，是制度失误。唯有时间可以消化之。
  
* 人的自控
  强调自控的不合理性。倒不如从心出发。自控是暂时的，想通是永恒的。

  自控能装模作样，想通能游刃有余。

  -- I Love The Earth. 

  -- 动漫真的没什么好看了

* 日漫的局限性
  人工作画总有一天，会消散于历史长河中。

  终有一日，蓝星上，文化主导权，将只会剩下三个喇叭。 [[https://movie.douban.com/subject/27148208/][西行记]]

* 本月总结  
  Emacs真好玩..dalao一点省十年

  PLA无论在递推样式上和收敛性证明上都好好看

  Python真无聊耶..orz

  荣耀手环4 -- 带个手环敲键盘，都感觉自己的手特别稳了不少，嘻嘻。
  
