#+TITLE: 财务自由之路

* 生活的五个坐标：健康、财务、与人间的关系、情感生活和人生的意义
** 健康
   显然，健康是一切的根基。脱离了健康，一切皆为虚无。

   但实在而言，健康的剥夺的再获取其成本是极度高昂的。
** 财务
   财务的重要性，一言以蔽之 -> 思想及肉体的自由度的唯一决定因素。


** 人间关系

** 情感生活
** 人生的意义

* 1000万是个奇迹吗
** 创造奇迹的5个层次
*** 1st: 对于现状的极度不满 -> 对于现今自身所处的处境感到难堪
*** 2nd: 期望的结果没有出现 -> 认识到目前的决策并不足以达成目标
*** 3th: 具有影响力的朋友
*** 4th: 多加思考，打破思维定势，拒绝盲从
    许多人不加思考就把世界想像成丛林，认为需要通过尖利的爪牙才能生存。

    而至于为何许多人会养成这种思维方式，或许因为人有倾向于放大自己的不幸以获取更大的安慰。

    而又因为这种倾向本身具有极优良的潜藏性，因而这种倾向的获得是普遍的。

    如果我们使用非黑即白的眼光来看待世界，那么肯定也有其他的“眼睛”使我们的生活更加幸福。那些“眼睛”让我们看到机会，

    而不是错误和陷阱。
*** 5th: 改变自身认知，带来巨大改变
    我们的自我认识实际上就是对自我实现的预言
** 如何创造奇迹 -- 奇迹是与个人经验相矛盾的事实
*** 不断学习和成长
**** 书籍、个人成功日记、讲座以及榜样
***** 书籍
      低成本的继承长时间跨度的经验的最佳手段
***** 个人成功日记
      于我个人，我的个人分析，是否需要日记呢？

      我个人倾向于不断回味痛苦。的确，思维上的自虐倾向。东亚人通病？

      于是是否是必要的呢？创意日记、关系日记、认识日记、其他日记。日后再说。
***** 讲座
      讲座某程度类似于书籍，只是在讲座中，经多感官刺激，学习效果也许会更好。

      同时，讲座将我们从日常事务中解脱出来，应而使得我们可以远距离的观察自己。
***** 榜样
      几乎所有的知识和技能都是通过模仿学习的。环境对我们的影响远超于我们的认知。

      因而，树立一个良好的榜样，其影响是远超书籍和一切课程的。
* 为什么没有更多的人致富
  在德国从22岁开始，在65岁成为百万富翁的概率是0.2%。

  因为与成功学相比较，保持一定的温饱的生活并不讨人厌。且后者显然是更加舒适且轻松的。
** 你为什么是穷人
*** 穷人看钱如雾里看花
    财富的定义应当是准确的，我们必须用明确的数字来表达财富对于个人的意义。

    确定的金钱以及实现这个目标的时间: 在xxxx年我将拥有xxxx。

    定义财富的三个要求：明确的数目，记录总数，并可以形象地加以想象。
